import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Provider";
import { ShoppingCartModal } from "./components/ShoppingCartModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body >
        <CartProvider>
          <Navbar />
          <ShoppingCartModal />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
